"""Add datamarts

Revision ID: ad56aa7daca3
Revises: 655b02cf6069
Create Date: 2025-03-16 15:34:47.498603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad56aa7daca3'
down_revision: Union[str, None] = '655b02cf6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_efficiency',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.String(length=255), nullable=False),
    sa.Column('first_message_dt', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_message_dt', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('support_messages', sa.Integer(), nullable=False),
    sa.Column('user_messages', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_min', sa.Numeric(), nullable=True),
    sa.Column('etl_valid_from', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk__support_efficiency'))
    )
    op.create_table('user_activity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sessions_cnt', sa.Integer(), nullable=False),
    sa.Column('avg_pages_visited', sa.Numeric(), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('days_active_last_month', sa.Integer(), nullable=False),
    sa.Column('reviews_cnt', sa.Integer(), nullable=False),
    sa.Column('preferred_category', sa.String(length=255), nullable=True),
    sa.Column('etl_valid_from', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__user_activity'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    op.drop_table('support_efficiency')
    # ### end Alembic commands ###